### ISSUE TITLE
You can take over other accounts easily  - peatio can be hacked easily

### ISSUE THREAD

**Issue by italiangirl** [peatio/peatio#398] opened 2015-01-07 23:56 UTC
confidential, sorry!

**Comment by janx** [comment] 2015-01-08 03:53
Cannot reproduce. Are you sure you're logged out when you try to signup?

**Comment by Jarinzbazin** [comment] 2015-01-08 09:00
Working.. After sends new register form.. Next login not works

**Comment by italiangirl** [comment] 2015-01-08 10:51
Inside the members table there is a field named: email. This is used for sign up and sign in to identify users. The problematic thing is the so called COLLATION of that field which is set to: uft8_unicode_ci.... Thats bad! Because its not case sensitive. Better solution would be to set this field to Collation: utf8_bin. It needs to be a kind of binary. Only then it would be more case sensitive. 

If that mysql field is not set to collation binary, then mysql will not perform case sensitive queries. 
Actually, this problem is not necessarily reproducible at all Versions of mysql, I assume.....
I could also be wrong. i am sorry....

But still, case sensitivity is a important topic. IMHO
And we should never let a user be able to sign up as NiceMaria@gmail.com and again at nicemaria@gmail.com. Yous see. Thats all problematic.....

best greetings from italy

**Comment by janx** [comment] 2015-01-08 16:02
@italiangirl @Jarinzbazin problem confirmed, fixed on master.

We hide the report here since it may affect running Peatio exchanges, we'll notify all of them immediately.

@italiangirl thank you very much for the report. Could you give us your btc address by sending an email to security@peatio.com? We want to send you a little reward.

Best Regards.

**Closed by janx** 2015-01-08 16:02 UTC

**Comment by italiangirl** [comment] 2015-01-08 19:19
thanks, 

I will send you an email
sunny greetings from Italy
